@startuml
class Virtual_Desktop {

afiseaza()
}
class Icons {
}
class Buton_SMS_Icon {
}
class Button_CALL_LOG_Icon {
}
class Button_FILES_Icon {
}
class Profile {
}
class Buton_respingere {
Conexiune
Dimensiune
Text
Status
Disable
Afiseaza ()
Schimba_culoare ()
}
class Telefon {
}
class Laptop_PC {
}
class Conexiune {
}

class Mesaj_securitate {
Conexiune
Device
Accepta_conexiune ()
Respinge_conexiune ()
}
class Mesaj {
Conexiune
Buton_Name
Save_phone_for_further_connections?()
Accept()
Decline()
}

class Adresa_IP_telefon {
Valoare
Salveaza_Valoare_in_Memoria Cache ()
}

class Lista {
Device
View_last_3_saved_devices()
}


class button_Accept{
Yes
No
afiseaza()
}
popup *-- Button
popup *-- Button_continue_with_my_session
popup *-- Button_Log_out
popup *-- Notification_popup
popup *-- button_Accept
popup *-- Buton_respingere
popup *-- Mesaj
Settings *-- notification_popup
popup *-- LogIn
Menu .. User
Settings *- Desktop_Color
Settings *-- Icons_Size
Settings *-- Icons
Settings *-- Menu
Settings *-- Dropdwon_list
Virtual_Desktop *-- Button_FILES_Icon
Virtual_Desktop *-- Buton_SMS_Icon
Virtual_Desktop *-- Button_CALL_LOG_Icon
Virtual_Desktop -- Profile




class Button_Log_out {
afiseaza()
Yes
No
}
class Button_continue_with_my_session {
afiseaza ()
Select ()
Text
Dimensiune
Culoare

}

class Icons_Size {
small
medium
large
afiseaza()
salveaza()
}

class Desktop_Color {
afiseaza()
salveaza()
black
gray
Wallpaper
}

class Icons {
sorteaza()
salveaza()
A_to_Z
Z_to_A
}

class Menu{
afiseaza()
modifica()
schimba_dimensiune_icoane()
Icons_Size
User
Desktop_Color
Icons
Time_to_show_popup
}


class notification_popup {
time
notification_popup
salveaza()
change()
disable()
afiseaza()
}

class User {
name
password
nr_max_caractere
afiseaza()
salveaza_inpunt()
sterge_username()
limiteaza_numar_caractere_la_16()
}
class Dropdwon_list {
Lista
afiseaza()
selecteaza()
}

class popup {
}

class Settings {
}

class Status_of_connection {
Status_connected
Culoare
Transparenta
afiseaza()
inchide()
}
class fereastra_noua {
}
class Button {
Yes
No

afiseaza()
}

class Notification_popup {
SMS received
Missed Phone Call
afiseaza()
}
class information {
contacte
SMS
}
fereastra_noua *-- information
Buton_SMS_Icon .. fereastra_noua : click pe icoana
Button_CALL_LOG_Icon .. fereastra_noua : click pe icoana
Button_FILES_Icon .. fereastra_noua : click pe icoana

class LogIn{
Yes
No
afiseaza()
selecteaza()
}


Conexiune *-- Telefon
Conexiune *-- Laptop_PC


@enduml