@startuml
skinparam actorStyle awesome
User -->(Generate IP adress) :- connect phone & Laptop to WiFi
User --> (display popup screen\nconnection message) :- Click Accept / Click Decline
User --> (display status of connection\n in a popup window) :- Succsessful connection / Connection declined
User -->(view list in a popup window\nwith last 3 saved phones\nand virtual desktop) :- click yes
User -->(view only virtual desktop\nwith icons) :- click no
User --> (After virtual desktop was generated\nthe user can see on the left of the screen\na dropdown menu with settings of the app)
:User: -up-> (display icons\non virtual desktop)
:User: -up-> (view SMS as TEXT in\na new popup screen) :- double ckick on\nSMS icon
:User: -up-> (display call log as TEXT in\na new popup screen) :- double click on\nTEXT icon
:User: -left-> (view dropdown menu with settings, where\nuser can change\ndesktop color\nchange icon size\nsort icons by name, or by the last icon that has been accessed\nchange notification timing message\nturn off notification message) :- click "MENU" on the left side of the screen\n then Settings
:User: -down-> (view popu screen with message\nsave phone for further connections?) :- options to click:\n*yes\n*no
:User: -down-> (if user clicks on "yes"\nthen view popup screen\nand give options to create\new user)
:User: -up-> (display in a popup window\nicons that represent the saved files, pictures and movies\nthat cat be downloaded on the PC) :-double click on\nFILES icon
:User: -right-> (-->display popup screen with message\n "continue_with_my_session") :- click on below message\n to continue with the active\n session
:Timer: -up-> (If virtual desktop has more than\n 5 minutes of inactivity, display\n message that the connection\n will be interrupted in the following\n 30 seconds)
:User: -up--> (view popu screen with message\n "are you sure you want to close this session?") :- click on\n Log out\n button
:User: -down-> (display popup screen\n*SMS phone notification\n*Missed Phone Call)

@enduml